### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by cool-Blue** [notbobutah/CoreValues#1]
Missing a pesky semicolon in psql-ddl.sql

```sql
CREATE TABLE ValueSet (
  id SERIAL PRIMARY KEY,
  PARENT_ID INTEGER,
  name VARCHAR,
  ext_user_id VARCHAR,
  ext_system_id VARCHAR
) -- <~~~~ missing semicolon
CREATE TABLE corevalue_defs (
  ID SERIAL PRIMARY KEY,
  PARENT_ID integer,
  name VARCHAR,
  lastUpdated TIMESTAMP,
  Dict_definition VARCHAR
);
```

**Comment by notbobutah** [comment]
The file ddl.sql is generated from the postgres export function and is accurate, I have dropped the competing files.

Please use CoreValues/db/ddl.sql

**Comment by cool-Blue** [comment]
No problem Rob, I was just really happy to finally get Postgres going without error. I ended up using pg to build the database directly in javascript so  I used most of your ddl file to build the table out. Can you please let me know if it builds ok? It's important to make sure that there are no connections to the database.
